---
- hosts: localhost
  vars_files:
    - vars_files/connections.yaml
  tasks:
    - uri: |
        url="{{ es_address }}/{{ item.p }}"
        method=PUT
        body_format=json
        HEADER_Content-Type=application/json
        body={{ lookup('file', item.f) }}
        status_code=200,201
      with_items:
        - { f: 'sample-logs/1.json', p: 'logs-2016.05.27/amiast/1' }
        - { f: 'sample-queries/news.json', p: 'stored-query/.percolator/news' }
      name: "filling fake data"

    - uri: |
        url="{{ es_address }}/stored-query/amiast/_percolate"
        method=GET
        body_format=json
        HEADER_Content-Type=application/json
        body={{ lookup('file', 'query-dsl/percolate.json') }}
        status_code=200
      register: percolate_result
      until: percolate_result.json.matches|length > 0
      retries: 5
      delay: 2
      name: "percolate query testing"

    - set_fact:
        percolate_failed: (percolate_result.json.matches[0]._id != 'news')
      name: "collecting result"

    - debug: var=percolate_result.json.matches
      when: percolate_failed
      name: "hits of percolate result"

    - fail:
        msg: "unexpected percolate search result"
      when: percolate_failed
      name: "abort when percolating reach retries"
