# Default values for inu-es-env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: henryrao/inuesenv
  tag: 5.3
  pullPolicy: IfNotPresent
playbooks:
  - "logs-index-template.yaml"
  - "stored-query-config.yaml"