apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "setup-%s-%s" .Chart.Name .Release.Name | trunc 63 }}
spec:
  template:
    metadata:
      name: {{ printf "setup-%s-%s" .Chart.Name .Release.Name | trunc 63 }}
    spec:
      containers:
      - name: ansible
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: ELASTICSEARCH_ADDR
            value: {{ printf "%s.%s.svc.cluster.local" .Values.elasticsearch.service.name .Release.Namespace }} 
          - name: ELASTICSEARCH_PORT
            value: "9200"
        command:
          - "ansible-playbook"
          {{- range .Values.playbooks }}
          - {{ . | quote }}
          {{- end }}
      restartPolicy: OnFailure

